### ISSUE TITLE
[TODO] 남은 부분

### ISSUE THREAD

**Issue by meixploit** [RO-AD/waypoint-maker#2]
### TO DO List
- [x]  어떤 API 사용할지 정하기 (네이버, 구글, 카카오)
- [x]  API 사용해서 지도 불러오기
- [x]  지도를 클릭했을 때 위치 마커로 표시하기
- [x]  해당 위치의 위도, 경도(GPS 값) 불러오기
- [x]  위/경도 값 UTM 좌표계로 변환
- [x]  지도 위 마커 클릭할 때마다 표시 (여러 개)
- [x] 마커 클릭 시 삭제하기
- [x] 좌표 클릭 시 분할하여 WP 생성
- [x] WP 정리해서 파일로 내보내기
- [x] 실제 GPS와 프로그램 좌표의 오차 범위 확정짓기
- [x] 도메인 구축하기 (https://ro-ad.kr/waypoint-maker/)
- [x] KGU와 KCITY 지점으로 이동하는 버튼 제작
- [x] 스카이뷰 전환 버튼
- [x] Initialize 버튼 활성화
- [x] waypoint 입력하면 marker로 변환

### 선택
- [ ] 클릭한 좌표값들 선으로 잇기 
- [ ] waypoint 파일 올리면 marker로 변환
- [ ] 위도/경도 리스트를 업로드하면, waypoint 파일로 받을 수 있도록 하는 기능
